In [19]:
from scipy import stats
stats.binom(n=1,p=0.5).rvs(size=1) #random variable sample
#stats.bernoulli(p=0.5).rvs(size=1)

array([1])

In [10]:
for i in range(10):
    if stats.binom(n=1,p=0.5).rvs(size=1) == 1:
        print('I print when `i` is', i)

I print when `i` is 1
I print when `i` is 2
I print when `i` is 4
I print when `i` is 5
I print when `i` is 6
I print when `i` is 7
I print when `i` is 8
I print when `i` is 9


In [12]:
alpha,beta,n,x=1,1,10,5 # n=number of trials, x=success
beta_distribution = stats.beta(a=1,b=1)
beta_distribution.pdf(0.5)

0.9999999999999996

In [18]:
import numpy as np; import matplotlib.pyplot as plt
parameter_domain = np.linspace(0,1,1001)
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

### data 2

In [20]:
stats.binom(n=1,p=0.3).rvs(size=1)

array([1])

In [22]:
for i in range(10):
    if stats.binom(n=1,p=0.3).rvs(size=1) == 1:
        print('I print when `i` is', i)

I print when `i` is 1
I print when `i` is 5
I print when `i` is 7


In [23]:
alpha,beta,n,x=1,1,10,5
beta_distribution = stats.beta(a=1,b=1)
beta_distribution.pdf(0.3)

0.9999999999999996

### data 3

In [26]:
stats.binom(n=1,p=0.6).rvs(size=1)

array([0])

In [27]:
for i in range(10):
    if stats.binom(n=1,p=0.6).rvs(size=1) == 1:
        print('I print when `i` is', i)

I print when `i` is 2
I print when `i` is 4
I print when `i` is 7
I print when `i` is 9


In [28]:
alpha,beta,n,x=1,1,10,5
beta_distribution = stats.beta(a=1,b=1)
beta_distribution.pdf(0.6) #plausibility that 0.6 is true probability

0.9999999999999997

In [ ]:
## simulation 1 (0.6)

In [47]:
simulation_results_1 = stats.binom(n=10,p=0.6).rvs(size=1)
x=np.sum(simulation_results_1)
n=10

In [49]:
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

In [54]:
prior

array([0.00000000e+00, 4.94010495e-22, 1.26213627e-19, ...,
       1.94854088e-03, 4.91053832e-04, 0.00000000e+00])

In [55]:
posterior

array([0.00000000e+00, 4.94010495e-22, 1.26213627e-19, ...,
       1.94854088e-03, 4.91053832e-04, 0.00000000e+00])

In [53]:
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.6)

1.3302558719999986

In [ ]:
## simulation 2 (0.5)

In [57]:
simulation_results_2 = stats.binom(n=10,p=0.5).rvs(size=1)
x=np.sum(simulation_results_2)
n=10

In [58]:
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

In [59]:
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.5)

2.7070312500000004

In [ ]:
## simulation 3 (0.3)

In [60]:
simulation_results_3 = stats.binom(n=10,p=0.3).rvs(size=1)
x=np.sum(simulation_results_3)
n=10

In [61]:
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

In [62]:
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.3)

1.3316690309999988

In [ ]:
## simulation 4 (0.6)

In [63]:
simulation_results_4 = stats.binom(n=100,p=0.6).rvs(size=1)
x=np.sum(simulation_results_4)
n=100

In [64]:
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

In [65]:
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.6)

4.8289291904390845

In [66]:
simulation_results_5 = stats.binom(n=100,p=0.5).rvs(size=1)
x=np.sum(simulation_results_5)
n=100

In [67]:
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

In [68]:
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.5)

7.42622805107745

In [93]:
simulation_results_6 = stats.binom(n=100,p=0.3).rvs(size=1)
x=np.sum(simulation_results_6)
n=100

In [94]:
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)

In [95]:
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.3)

8.641717236714602

In [101]:
simulation_results_7 = stats.binom(n=200,p=0.3).rvs(size=1)
x=np.sum(simulation_results_7)
n=200
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.3)

11.254309686260063

In [102]:
simulation_results_8 = stats.binom(n=200,p=0.6).rvs(size=1)
x=np.sum(simulation_results_8)
n=200
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.6)

6.006315592753466

In [103]:
simulation_results_9 = stats.binom(n=200,p=0.5).rvs(size=1)
x=np.sum(simulation_results_9)
n=200
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.5)

8.830821050184086

In [104]:
simulation_results_7 = stats.binom(n=700,p=0.3).rvs(size=1)
x=np.sum(simulation_results_7)
n=700
likelihood = stats.binom.pmf(n=n, k=x, p=parameter_domain)
prior = stats.beta(a=alpha,b=beta).pdf(parameter_domain)
posterior = stats.beta(a=x+alpha,b=n-x+beta).pdf(parameter_domain)
beta_distribution = stats.beta(a=x+alpha,b=n-x+beta)
beta_distribution.pdf(0.3)

13.983452411313738

The data I chose are 0.3, 0.5 and 0.6. I tried simulations of their binomial distributions, with increasing number of distributions. I found 0.3 to be the best. 